In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
ls

data/  intro_python_notebook.ipynb


In [11]:
cd data

/home/justin/Desktop/python-novice-inflammation/data


In [12]:
pwd

'/home/justin/Desktop/python-novice-inflammation/data'

In [13]:
ls

inflammation-01.csv  inflammation-05.csv  inflammation-09.csv  small-01.csv
inflammation-02.csv  inflammation-06.csv  inflammation-10.csv  small-02.csv
inflammation-03.csv  inflammation-07.csv  inflammation-11.csv  small-03.csv
inflammation-04.csv  inflammation-08.csv  inflammation-12.csv


In [37]:
my_array = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [28]:
this_is_confusing = np.loadtxt

In [29]:
this_is_confusing(fname='inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [18]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_import_tools',
 '_mat',
 'abs',
 'absolut

In [26]:
help(np.loadtxt)

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file or str
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence, optional
        The characters or list of characters us

In [31]:
print(my_array)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [32]:
whos

Variable            Type        Data/Info
-----------------------------------------
my_array            ndarray     60x40: 2400 elems, type `float64`, 19200 bytes
np                  module      <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
numpy               module      <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
plt                 module      <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
this                module      <module 'this' from '/hom<...>3/lib/python3.5/this.py'>
this_is_confusing   function    <function loadtxt at 0xaf67514c>


In [39]:
type(my_array)

numpy.ndarray

In [41]:
my_array.dtype

dtype('float64')

In [42]:
dir(my_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

In [49]:
my_array.shape

(60, 40)

In [51]:
oned_array = np.array([1, 2, 3, 4, 5])

In [53]:
oned_array[0]

1

In [55]:
twod_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [56]:
twod_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [58]:
twod_array[0, 1]

2

In [66]:
threed = np.zstack([twod_array, twod_array])

AttributeError: module 'numpy' has no attribute 'zstack'

In [71]:
my_array

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

### Exercise

Create the row-sum and column-sum arrays from this data.

You will need: dir()  help()

In [77]:
my_array.sum(1)

array([ 218.,  217.,  244.,  236.,  222.,  249.,  239.,  266.,  265.,
        261.,  271.,  232.,  249.,  230.,  209.,  252.,  262.,  228.,
        234.,  262.,  231.,  233.,  247.,  244.,  232.,  257.,  242.,
        241.,  247.,  262.,  247.,  254.,  269.,  245.,  283.,  229.,
        237.,  246.,  243.,  230.,  239.,  229.,  252.,  236.,  270.,
        237.,  289.,  246.,  238.,  251.,  228.,  244.,  273.,  239.,
        269.,  228.,  250.,  256.,  282.,  236.])

In [79]:
my_array.mean(axis=1)

array([ 5.45 ,  5.425,  6.1  ,  5.9  ,  5.55 ,  6.225,  5.975,  6.65 ,
        6.625,  6.525,  6.775,  5.8  ,  6.225,  5.75 ,  5.225,  6.3  ,
        6.55 ,  5.7  ,  5.85 ,  6.55 ,  5.775,  5.825,  6.175,  6.1  ,
        5.8  ,  6.425,  6.05 ,  6.025,  6.175,  6.55 ,  6.175,  6.35 ,
        6.725,  6.125,  7.075,  5.725,  5.925,  6.15 ,  6.075,  5.75 ,
        5.975,  5.725,  6.3  ,  5.9  ,  6.75 ,  5.925,  7.225,  6.15 ,
        5.95 ,  6.275,  5.7  ,  6.1  ,  6.825,  5.975,  6.725,  5.7  ,
        6.25 ,  6.4  ,  7.05 ,  5.9  ])

In [80]:
np.mean(my_array, axis=1)

array([ 5.45 ,  5.425,  6.1  ,  5.9  ,  5.55 ,  6.225,  5.975,  6.65 ,
        6.625,  6.525,  6.775,  5.8  ,  6.225,  5.75 ,  5.225,  6.3  ,
        6.55 ,  5.7  ,  5.85 ,  6.55 ,  5.775,  5.825,  6.175,  6.1  ,
        5.8  ,  6.425,  6.05 ,  6.025,  6.175,  6.55 ,  6.175,  6.35 ,
        6.725,  6.125,  7.075,  5.725,  5.925,  6.15 ,  6.075,  5.75 ,
        5.975,  5.725,  6.3  ,  5.9  ,  6.75 ,  5.925,  7.225,  6.15 ,
        5.95 ,  6.275,  5.7  ,  6.1  ,  6.825,  5.975,  6.725,  5.7  ,
        6.25 ,  6.4  ,  7.05 ,  5.9  ])

## Slicing

array[start:stop:step]

Indexing is 0 to N-1

In [ ]:
my_array[start:stop:step, start:stop:step]

In [81]:
my_array[:, 0].mean()

0.0

In [82]:
my_array[::2].mean()

6.2341666666666669

In [94]:
my_array[-1, -1]

0.0

# Slicing works on more than arrays

In [96]:
my_name = "Justin Ely"

In [116]:
# slicing
my_name[::-1]

'ylE nitsuJ'

In [113]:
# indexing
my_name[-2]

'l'

In [119]:
my_list = [1, 2, "hello", np.max]

In [120]:
my_list

[1, 2, 'hello', <function numpy.core.fromnumeric.amax>]

In [121]:
type(my_list)

list

In [122]:
my_list[::-1]

[<function numpy.core.fromnumeric.amax>, 'hello', 2, 1]

In [135]:
my_list = [1, 2, 3, 4, 5]

In [141]:
my_tup = (1, (2, 4), 3, 4, 5)

In [137]:
my_list[0] = 5

In [138]:
my_list

[5, 2, 3, 4, 5]

In [142]:
my_tup

(1, (2, 4), 3, 4, 5)

In [143]:
my_tupe = tuple([1, 2, 3, 4])

In [144]:
my_tupe

(1, 2, 3, 4)

## Slicing, indexing, etc

1. Create a string of your name and your favorite ice cream.  
  *  print it in reverse
  *  slice your name apart from the ice-cream flavor
  
2. Create a list of 5 people from the class.
  *  figure out how to add another student to the end
  *  figure out how to remove a student from the beginning
     * dir(), help(), internet for help

In [146]:
students = ["James", "James2", "Cindy", "Cindy2"]

In [147]:
students_plus_one = students.append("Bob")

In [148]:
students

['James', 'James2', 'Cindy', 'Cindy2', 'Bob']

In [150]:
type(students_plus_one)

NoneType

In [154]:
students = students + ["Bob2"]

In [155]:
students

['James', 'James2', 'Cindy', 'Cindy2', 'Bob', 'Bob2']

In [156]:
students.pop(0)

'James'

In [158]:
students

['James2', 'Cindy', 'Cindy2', 'Bob', 'Bob2']

In [159]:
name = students.pop(0)

In [160]:
name

'James2'

In [161]:
dir(students)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [162]:
students

['Cindy', 'Cindy2', 'Bob', 'Bob2']

In [163]:
students.sort()

In [164]:
students

['Bob', 'Bob2', 'Cindy', 'Cindy2']

In [165]:
students = students[::-1]

In [168]:
print(sorted(students))

['Bob', 'Bob2', 'Cindy', 'Cindy2']


### set

In [169]:
a = {1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6}

In [170]:
type(a)

set

In [171]:
a

{1, 2, 3, 4, 5, 6}

In [172]:
a = {1, 2, '3', 'frog', 'frog'}

In [173]:
a

{1, 'frog', 2, '3'}

In [174]:
a

{1, 'frog', 2, '3'}

In [175]:
b = a

In [176]:
b

{1, 'frog', 2, '3'}

In [177]:
a[0]

TypeError: 'set' object does not support indexing

### Excercise

1.  given {1, 2, 3, 4, 5, 6, 7, 8, 9} and a set {1, 2, 3}, print the set {4, 5, 6, 7, 8, 9}

2.  Produce the union of {1, 'flew', 'over'} and {'over', 'the', 1, 'cuckoos', 'nest'}

In [180]:
a = {1, 2, 3, 4, 5, 6, 7, 8, 9}
b = {1, 2, 3}

In [181]:
a.difference(b)

{4, 5, 6, 7, 8, 9}

In [182]:
a - b

{4, 5, 6, 7, 8, 9}

In [183]:
a

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [184]:
a = {1, 'flew', 'over'} 
b = {'over', 'the', 1, 'cuckoos', 'nest'}

In [185]:
a.union(b)

{1, 'cuckoos', 'flew', 'the', 'nest', 'over'}

In [188]:
a | b

{1, 'cuckoos', 'flew', 'the', 'nest', 'over'}

In [191]:
my_list = [(1, 2), (1, 2), (3, 4)]

In [192]:
my_list = list(set(my_list))

In [193]:
my_list

[(1, 2), (3, 4)]